#!/usr/bin/env python3
"""第二輪翻譯：用 XML 解析器精確處理 + 更大的片語字典"""
import xml.etree.ElementTree as ET
import re, copy

TS_PATH = '/Users/ktw/ktw-projects/fincept-terminal-zh/fincept-qt/translations/fincept_zh_TW.ts'

# 片語級翻譯字典（source → translation）
PHRASES = {
    # UI 動作
    "(no events recorded yet)": "(尚無已記錄的事件)",
    "(no portfolios yet)": "(尚無投資組合)",
    "+ ADD": "+ 新增", "+ Add": "+ 新增", "+ New": "+ 新增",
    "+ ADD CONNECTION": "+ 新增連線",
    "+ ADD CURRENT SERIES": "+ 新增目前序列",
    "+ ADD SLOT": "+ 新增插槽",
    "+ ADD TO SELECTION": "+ 新增至選取",
    "+ ADD TO TEAM": "+ 新增至團隊",
    "+ ADVANCED": "+ 進階",
    "+ Add Tag Override": "+ 新增標籤覆寫",
    "+ CREATE NEW": "+ 建立新項目",
    "+ Import": "+ 匯入",
    "+ NEW": "+ 新增", "+ NEW MAPPING": "+ 新增對應",
    "+ NEW POST": "+ 新建貼文",
    "-- BULL": "-- 看漲", "-- NEUTRAL": "-- 中性",
    "--- RECENT TRADES ---": "--- 近期交易 ---",
    "0 INDICATORS": "0 個指標",
    "0 endpoints": "0 個端點",
    "0 lists": "0 個列表",
    "0 notes": "0 個筆記",
    "1 min": "1 分鐘", "5 min": "5 分鐘", "10 min": "10 分鐘",
    "15 min": "15 分鐘", "30 min": "30 分鐘", "60 min": "60 分鐘",
    "10 Years": "10 年", "5 Years": "5 年", "3 Years": "3 年",
    "1 Year": "1 年", "6 Months": "6 個月", "3 Months": "3 個月",
    "1 Month": "1 個月", "1 Week": "1 週", "1 Day": "1 天",
    "ABOUT": "關於", "About": "關於",
    "ACCESS KEY": "存取金鑰",
    "ACCOUNT OVERVIEW": "帳戶總覽",
    "ACTIVE ALERTS": "啟用中的警示",
    "ACTIVE CONNECTIONS": "連線中",
    "ACTIVE DEALS": "進行中的交易",
    "ACTIVE STRATEGIES": "啟用中的策略",
    "ADD ALERT": "新增警示",
    "ADD COLUMN": "新增欄位",
    "ADD CONDITION": "新增條件",
    "ADD FILTER": "新增篩選",
    "ADD INDICATOR": "新增指標",
    "ADD LAYER": "新增圖層",
    "ADD PANEL": "新增面板",
    "ADD POSITION": "新增部位",
    "ADD RULE": "新增規則",
    "ADD SERIES": "新增序列",
    "ADD TICKER": "新增股票代碼",
    "ADD TO WATCHLIST": "新增至觀察清單",
    "ADD WIDGET": "新增小工具",
    "ALL TIME": "所有時間",
    "ALL SECTORS": "所有類股",
    "ANALYZE": "分析", "Analyze": "分析",
    "API KEY": "API 金鑰",
    "API KEYS": "API 金鑰",
    "APPLY FILTER": "套用篩選",
    "APPLY STRATEGY": "套用策略",
    "ASSET ALLOCATION": "資產配置",
    "ASSET CLASS": "資產類別",
    "ASSET CLASSES": "資產類別",
    "ASSET OVERVIEW": "資產總覽",
    "AVERAGE RETURN": "平均報酬",
    "AWAITING DATA": "等待資料",
    "BACK TO LIST": "返回列表",
    "BACKTEST RESULTS": "回測結果",
    "BAR": "長條", "BARS": "長條",
    "BASE CURRENCY": "基礎貨幣",
    "BASIC INFO": "基本資訊",
    "BEARISH SIGNALS": "看跌訊號",
    "BEST PERFORMER": "最佳表現",
    "BLOCK EXPLORER": "區塊鏈瀏覽器",
    "BOLLINGER BANDS": "布林帶",
    "BOTTOM": "底部",
    "BREAKOUT ALERT": "突破警示",
    "BUY SIGNAL": "買入訊號",
    "CANCEL ORDER": "取消訂單",
    "CANDLE": "K線", "CANDLES": "K線",
    "CASH": "現金",
    "CHART TYPE": "圖表類型",
    "CLEAR ALL": "全部清除",
    "CLEAR FILTERS": "清除篩選",
    "CLOSE ALL": "全部關閉",
    "CLOSE POSITION": "平倉",
    "CLOSED": "已關閉", "Closed": "已關閉",
    "COLLAPSE ALL": "全部收合",
    "COMPARE": "比較", "Compare": "比較",
    "COMPLETED DEALS": "已完成的交易",
    "CONFIGURE": "設定", "Configure": "設定",
    "CONNECTED": "已連線",
    "CONNECTION ERROR": "連線錯誤",
    "CONTRIBUTORS": "貢獻者",
    "COPY API KEY": "複製 API 金鑰",
    "COPY LINK": "複製連結",
    "COST BASIS": "成本基礎",
    "COUNTRY": "國家", "Country": "國家",
    "CREATE ALERT": "建立警示",
    "CREATE ORDER": "建立訂單",
    "CREATE PORTFOLIO": "建立投資組合",
    "CREATE STRATEGY": "建立策略",
    "CREATE WATCHLIST": "建立觀察清單",
    "CROSS": "交叉",
    "CUMULATIVE RETURN": "累積報酬",
    "CURRENCY": "貨幣", "Currency": "貨幣",
    "CURRENT PRICE": "目前價格",
    "CURRENT VALUE": "目前價值",
    "CUSTOMIZE": "自訂",
    "DAILY CHANGE": "每日漲跌",
    "DAILY RETURN": "每日報酬",
    "DATA SOURCE": "資料來源",
    "DATA SOURCES": "資料來源",
    "DEAL FLOW": "交易流",
    "DEAL OVERVIEW": "交易總覽",
    "DEAL SIZE": "交易規模",
    "DEAL TYPE": "交易類型",
    "DEAL VALUE": "交易價值",
    "DEFAULT LAYOUT": "預設佈局",
    "DELETE ALL": "全部刪除",
    "DETAILS VIEW": "詳細檢視",
    "DISCONNECT": "中斷連線",
    "DIVIDEND HISTORY": "股息歷史",
    "DIVIDEND YIELD": "股息率",
    "EARNINGS CALENDAR": "財報行事曆",
    "ECONOMIC CALENDAR": "經濟行事曆",
    "EDIT LAYOUT": "編輯佈局",
    "EDIT STRATEGY": "編輯策略",
    "EMPTY": "空",
    "ENTER API KEY": "輸入 API 金鑰",
    "ENTRY PRICE": "進場價格",
    "ERROR LOADING DATA": "載入資料時發生錯誤",
    "EXECUTE": "執行",
    "EXECUTION LOG": "執行日誌",
    "EXIT PRICE": "出場價格",
    "EXPAND ALL": "全部展開",
    "EXPIRED": "已過期",
    "EXPLORER": "瀏覽器",
    "EXPORT CSV": "匯出 CSV",
    "EXPORT PDF": "匯出 PDF",
    "EXPORT REPORT": "匯出報告",
    "FAVORITES ONLY": "僅收藏",
    "FINANCIAL DATA": "財務資料",
    "FINANCIAL STATEMENTS": "財務報表",
    "FULL SCREEN": "全螢幕",
    "FUNDAMENTAL": "基本面",
    "FUNDAMENTALS": "基本面",
    "GAIN": "獲利", "GAINS": "獲利",
    "GENERATE": "產生", "Generate": "產生",
    "GENERATE REPORT": "產生報告",
    "GLOBAL": "全球",
    "GLOBAL MARKETS": "全球市場",
    "GO TO": "前往",
    "GRID": "網格", "GRID VIEW": "網格檢視",
    "GROUPED": "已分組",
    "HEALTH CHECK": "健康檢查",
    "HIGH RISK": "高風險",
    "HIGHEST": "最高",
    "HOLDINGS": "持倉",
    "HOURLY": "每小時",
    "IMPORT DATA": "匯入資料",
    "IN PROGRESS": "進行中",
    "INCOME": "收入", "Income": "收入",
    "INDEX FUNDS": "指數基金",
    "INITIAL INVESTMENT": "初始投資",
    "INTRADAY": "盤中",
    "INVEST": "投資",
    "KEY METRICS": "關鍵指標",
    "LAST PRICE": "最新價格",
    "LAST TRADE": "最近交易",
    "LAST UPDATED": "最後更新",
    "LATEST": "最新",
    "LAYOUT": "佈局",
    "LIST VIEW": "列表檢視",
    "LOADING DATA": "載入資料中",
    "LOADING...": "載入中...",
    "LOG": "日誌", "LOGS": "日誌",
    "LOW RISK": "低風險",
    "LOWEST": "最低",
    "MANAGE": "管理", "Manage": "管理",
    "MARKET DATA": "市場資料",
    "MARKET NEWS": "市場新聞",
    "MARKET OVERVIEW": "市場總覽",
    "MARKET STATUS": "市場狀態",
    "MAX DRAWDOWN": "最大回撤",
    "MEDIUM RISK": "中等風險",
    "MODIFY": "修改",
    "MONTHLY RETURN": "每月報酬",
    "MOVING AVG": "移動平均",
    "MULTI-ASSET": "多資產",
    "NET CHANGE": "淨變動",
    "NET POSITION": "淨部位",
    "NEW ALERT": "新警示",
    "NEW CONNECTION": "新連線",
    "NEW ORDER": "新訂單",
    "NEW STRATEGY": "新策略",
    "NEXT PAGE": "下一頁",
    "NO ALERTS": "無警示",
    "NO CONNECTION": "無連線",
    "NO DATA": "無資料",
    "NO DATA AVAILABLE": "無可用資料",
    "NO EVENTS": "無事件",
    "NO ITEMS": "無項目",
    "NO MATCHES": "無符合項目",
    "NO ORDERS": "無訂單",
    "NO POSITIONS": "無部位",
    "NO RESULTS": "無結果",
    "NOTIFICATION": "通知",
    "NOTIFY": "通知",
    "OPEN ORDERS": "未成交訂單",
    "OPEN POSITIONS": "未平倉部位",
    "ORDER BOOK": "委託簿",
    "ORDER HISTORY": "訂單歷史",
    "ORDER TYPE": "訂單類型",
    "OUTPERFORM": "跑贏",
    "PENDING DEALS": "待處理交易",
    "PENDING ORDERS": "待處理訂單",
    "PERCENT CHANGE": "百分比變動",
    "PLACE ORDER": "下單",
    "PORTFOLIO ANALYSIS": "投資組合分析",
    "PORTFOLIO OVERVIEW": "投資組合總覽",
    "PORTFOLIO VALUE": "投資組合價值",
    "POSITION SIZE": "部位大小",
    "PREFERENCES": "偏好設定",
    "PREV PAGE": "上一頁",
    "PREVIOUS PAGE": "上一頁",
    "PRICE ALERT": "價格警示",
    "PRICE CHANGE": "價格變動",
    "PRICE CHART": "價格圖表",
    "PRICE HISTORY": "價格歷史",
    "PRICE TARGET": "目標價格",
    "PRINT": "列印",
    "PROFIT/LOSS": "損益",
    "QUICK FILTER": "快速篩選",
    "QUOTE": "報價",
    "RANGE": "範圍",
    "REAL TIME": "即時",
    "REALIZED P&L": "已實現損益",
    "REBALANCE": "再平衡",
    "REFRESH DATA": "重新整理資料",
    "REGION": "地區", "Region": "地區",
    "REMOVE ALL": "全部移除",
    "RENAME": "重新命名",
    "RESET ALL": "全部重設",
    "RESET FILTERS": "重設篩選",
    "RESET LAYOUT": "重設佈局",
    "RESULTS": "結果",
    "RETURN ON EQUITY": "股東權益報酬率",
    "RETURNS": "報酬",
    "RISK ANALYSIS": "風險分析",
    "RISK LEVEL": "風險等級",
    "RISK SCORE": "風險分數",
    "RUNNING": "執行中",
    "SAVE AS": "另存為",
    "SAVE LAYOUT": "儲存佈局",
    "SAVE STRATEGY": "儲存策略",
    "SCAN": "掃描",
    "SEARCH RESULTS": "搜尋結果",
    "SECTOR ANALYSIS": "類股分析",
    "SECTOR OVERVIEW": "類股總覽",
    "SELL SIGNAL": "賣出訊號",
    "SETUP": "設定",
    "SHARE LINK": "分享連結",
    "SHOW ALL": "顯示全部",
    "SHOW MORE": "顯示更多",
    "SHOW LESS": "顯示較少",
    "SIGNAL STRENGTH": "訊號強度",
    "SORT BY": "排序依據",
    "SOURCE": "來源",
    "STACKED": "堆疊",
    "STANDARD": "標準",
    "START DATE": "開始日期",
    "END DATE": "結束日期",
    "STATISTICS": "統計",
    "STOP LOSS": "停損",
    "STRATEGY BUILDER": "策略建構器",
    "STRATEGY OVERVIEW": "策略總覽",
    "SUPPLY": "供給", "Supply": "供給",
    "SWITCH": "切換",
    "SYNC": "同步", "Sync": "同步",
    "SYSTEM": "系統",
    "TAKE PROFIT": "停利",
    "TARGETS": "目標",
    "TECHNICAL": "技術面",
    "TECHNICAL ANALYSIS": "技術分析",
    "TIME FRAME": "時間框架",
    "TIME RANGE": "時間範圍",
    "TIMEFRAME": "時間框架",
    "TODAY": "今日", "Today": "今日",
    "TOGGLE": "切換",
    "TOP": "頂部",
    "TOP GAINERS": "漲幅前列",
    "TOP LOSERS": "跌幅前列",
    "TOP MOVERS": "漲跌幅前列",
    "TOTAL ASSETS": "總資產",
    "TOTAL RETURN": "總報酬",
    "TOTAL VALUE": "總價值",
    "TRADE HISTORY": "交易歷史",
    "TRADING": "交易",
    "TRADING VIEW": "交易檢視",
    "TRANSACTION": "交易記錄",
    "TRANSACTIONS": "交易記錄",
    "UNDERPERFORM": "跑輸",
    "UNDO": "復原",
    "UNREALIZED P&L": "未實現損益",
    "UPCOMING": "即將到來",
    "UPLOAD FILE": "上傳檔案",
    "USD": "美元",
    "VERSION": "版本", "Version": "版本",
    "VOLUME ANALYSIS": "成交量分析",
    "WATCHLIST EMPTY": "觀察清單為空",
    "WEIGHT": "權重",
    "WEEKLY RETURN": "每週報酬",
    "WINNERS": "贏家",
    "LOSERS": "輸家",
    "WORST PERFORMER": "最差表現",
    "YEARLY RETURN": "年度報酬",

    # 長句
    "Error loading data": "載入資料時發生錯誤",
    "No data available for this period": "此期間無可用資料",
    "No matching results": "無符合的結果",
    "Click to add": "點擊以新增",
    "Select a ticker to view details": "選擇一個代碼以檢視詳細資訊",
    "Select an asset to begin analysis": "選擇一項資產以開始分析",
    "Enter a valid ticker symbol": "輸入有效的股票代碼",
    "Data is loading, please wait": "資料載入中，請稍候",
    "Connection established": "連線已建立",
    "Connection timed out": "連線逾時",
    "Server is not responding": "伺服器無回應",
    "Invalid credentials": "認證資訊無效",
    "Rate limit exceeded": "已超過速率限制",
    "Insufficient permissions": "權限不足",
    "Feature not available": "功能不可用",
    "Under construction": "建構中",
    "Market is closed": "市場已收盤",
    "Market is open": "市場開盤中",
    "Pre-market": "盤前",
    "After-hours": "盤後",
    "Trading halted": "交易暫停",
    "LAST 24H": "最近 24 小時",
    "LAST 7D": "最近 7 天",
    "LAST 30D": "最近 30 天",
    "LAST 90D": "最近 90 天",
    "LAST YEAR": "最近一年",
    "No trades today": "今日無交易",
    "Portfolio is empty": "投資組合為空",
    "Add assets to get started": "新增資產以開始",
    "Drag widgets to customize layout": "拖曳小工具以自訂佈局",
    "Press Esc to close": "按 Esc 關閉",
    "Double-click to edit": "雙擊以編輯",
    "Right-click for options": "右鍵以開啟選項",
    "Scroll to zoom": "滾動以縮放",
    "27 ANALYZERS": "27 個分析工具",
    "10 ASSET CLASSES": "10 個資產類別",
    "MULTI-ASSET ANALYTICS": "多資產分析",

    # 特殊格式/技術字串 — 保留原文即可
    "--:--:--": "--:--:--",
    "/100": "/100",
    "0 / 4000": "0 / 4000",
    "0 / 5": "0 / 5",
    "0/0": "0/0",
    "00:00:00": "00:00:00",
    "1 / 1": "1 / 1",
    "10M": "10M",
    "0x… (64 hex chars)": "0x… (64 個十六進位字元)",
}

def main():
    tree = ET.parse(TS_PATH)
    root = tree.getroot()
    
    translated = 0
    already_done = 0
    skipped = 0
    
    for context in root.findall('.//context'):
        for message in context.findall('message'):
            trans_elem = message.find('translation')
            source_elem = message.find('source')
            
            if trans_elem is None or source_elem is None:
                continue
            
            if trans_elem.get('type') != 'unfinished':
                already_done += 1
                continue
            
            source = source_elem.text or ''
            source_stripped = source.strip()
            
            # 嘗試精確匹配
            if source_stripped in PHRASES:
                trans_elem.text = PHRASES[source_stripped]
                del trans_elem.attrib['type']
                translated += 1
                continue
            
            # 嘗試大寫匹配
            if source_stripped.upper() in PHRASES:
                trans_elem.text = PHRASES[source_stripped.upper()]
                del trans_elem.attrib['type']
                translated += 1
                continue
            
            # 已含中文 → 直接移除 unfinished
            if re.search(r'[\u4e00-\u9fff]', source_stripped):
                del trans_elem.attrib['type']
                translated += 1
                continue
            
            skipped += 1
    
    # 寫回（保留 XML 宣告）
    tree.write(TS_PATH, encoding='unicode', xml_declaration=True)
    
    # 重新讀取計算剩餘
    with open(TS_PATH, 'r') as f:
        remaining = f.read().count('type="unfinished"')
    
    print(f"✅ 第二輪翻譯完成: {translated} 條")
    print(f"📊 剩餘 unfinished: {remaining} 條")
    print(f"⏭️ 跳過: {skipped} 條")

if __name__ == '__main__':
    main()
