#!/usr/bin/env python3
"""批量翻譯 fincept_zh_TW.ts 中的 unfinished 條目"""
import re, xml.etree.ElementTree as ET

TS_PATH = '/Users/ktw/ktw-projects/fincept-terminal-zh/fincept-qt/translations/fincept_zh_TW.ts'

# 金融 / UI 翻譯字典
DICT = {
    # === 通用 UI ===
    "LOADING": "載入中", "loading...": "載入中...", "Loading...": "載入中...",
    "Loading": "載入中", "CANCEL": "取消", "Cancel": "取消",
    "OK": "確定", "SAVE": "儲存", "Save": "儲存", "DELETE": "刪除",
    "Delete": "刪除", "EDIT": "編輯", "Edit": "編輯", "ADD": "新增",
    "Add": "新增", "CLOSE": "關閉", "Close": "關閉", "BACK": "返回",
    "Back": "返回", "NEXT": "下一步", "Next": "下一步",
    "SUBMIT": "提交", "Submit": "提交", "CONFIRM": "確認", "Confirm": "確認",
    "RESET": "重設", "Reset": "重設", "REFRESH": "重新整理", "Refresh": "重新整理",
    "SEARCH": "搜尋", "Search": "搜尋", "FILTER": "篩選", "Filter": "篩選",
    "APPLY": "套用", "Apply": "套用", "CLEAR": "清除", "Clear": "清除",
    "RETRY": "重試", "Retry": "重試", "DONE": "完成", "Done": "完成",
    "YES": "是", "Yes": "是", "NO": "否", "No": "否",
    "ON": "開", "OFF": "關", "ENABLE": "啟用", "DISABLE": "停用",
    "COPY": "複製", "Copy": "複製", "PASTE": "貼上", "Paste": "貼上",
    "EXPORT": "匯出", "Export": "匯出", "IMPORT": "匯入", "Import": "匯入",
    "DOWNLOAD": "下載", "Download": "下載", "UPLOAD": "上傳", "Upload": "上傳",
    "REMOVE": "移除", "Remove": "移除", "SELECT": "選取", "Select": "選取",
    "SETTINGS": "設定", "Settings": "設定", "OPTIONS": "選項", "Options": "選項",
    "HELP": "說明", "Help": "說明", "INFO": "資訊", "Info": "資訊",
    "WARNING": "警告", "Warning": "警告", "ERROR": "錯誤", "Error": "錯誤",
    "SUCCESS": "成功", "Success": "成功",
    "hidden": "隱藏", "HIDDEN": "隱藏",
    "Name": "名稱", "NAME": "名稱",
    "Type": "類型", "TYPE": "類型",
    "Status": "狀態", "STATUS": "狀態",
    "Date": "日期", "DATE": "日期",
    "Time": "時間", "TIME": "時間",
    "Value": "數值", "VALUE": "數值",
    "Price": "價格", "PRICE": "價格",
    "Total": "合計", "TOTAL": "合計",
    "Amount": "金額", "AMOUNT": "金額",
    "None": "無", "NONE": "無", "N/A": "不適用",
    "Details": "詳細資訊", "DETAILS": "詳細資訊",
    "Summary": "摘要", "SUMMARY": "摘要",
    "Overview": "總覽", "OVERVIEW": "總覽",
    "Description": "說明", "DESCRIPTION": "說明",
    "Actions": "操作", "ACTIONS": "操作",
    "More": "更多", "MORE": "更多",
    "Less": "收起", "LESS": "收起",
    "Show": "顯示", "SHOW": "顯示",
    "Hide": "隱藏", "HIDE": "隱藏",
    "Sort": "排序", "SORT": "排序",
    "Group": "群組", "GROUP": "群組",
    "View": "檢視", "VIEW": "檢視",
    "Create": "建立", "CREATE": "建立",
    "Update": "更新", "UPDATE": "更新",
    "Send": "發送", "SEND": "發送",
    "Share": "分享", "SHARE": "分享",
    "Start": "開始", "START": "開始",
    "Stop": "停止", "STOP": "停止",
    "Pause": "暫停", "PAUSE": "暫停",
    "Resume": "繼續", "RESUME": "繼續",
    "Run": "執行", "RUN": "執行",
    "Test": "測試", "TEST": "測試",
    "Connect": "連線", "CONNECT": "連線",
    "Disconnect": "中斷連線", "DISCONNECT": "中斷連線",
    "Login": "登入", "LOGIN": "登入",
    "Logout": "登出", "LOGOUT": "登出",
    "Sign In": "登入", "SIGN IN": "登入",
    "Sign Out": "登出", "SIGN OUT": "登出",
    "Sign Up": "註冊", "SIGN UP": "註冊",
    "Register": "註冊", "REGISTER": "註冊",
    "Profile": "個人檔案", "PROFILE": "個人檔案",
    "Account": "帳戶", "ACCOUNT": "帳戶",
    "Dashboard": "儀表板", "DASHBOARD": "儀表板",
    "Home": "首頁", "HOME": "首頁",
    "Notifications": "通知", "NOTIFICATIONS": "通知",
    "Messages": "訊息", "MESSAGES": "訊息",
    "History": "歷史", "HISTORY": "歷史",
    "Favorites": "收藏", "FAVORITES": "收藏",
    "Bookmarks": "書籤", "BOOKMARKS": "書籤",
    "Recent": "最近", "RECENT": "最近",
    "Popular": "熱門", "POPULAR": "熱門",
    "Trending": "趨勢", "TRENDING": "趨勢",
    "New": "新增", "NEW": "新增",
    "All": "全部", "ALL": "全部",
    "Custom": "自訂", "CUSTOM": "自訂",
    "Default": "預設", "DEFAULT": "預設",
    "Advanced": "進階", "ADVANCED": "進階",
    "Basic": "基本", "BASIC": "基本",
    "General": "一般", "GENERAL": "一般",
    "Language": "語言", "LANGUAGE": "語言",
    "Theme": "主題", "THEME": "主題",
    "Dark": "深色", "DARK": "深色",
    "Light": "淺色", "LIGHT": "淺色",
    "Auto": "自動", "AUTO": "自動",
    "Manual": "手動", "MANUAL": "手動",
    "Enabled": "已啟用", "ENABLED": "已啟用",
    "Disabled": "已停用", "DISABLED": "已停用",
    "Active": "活躍", "ACTIVE": "活躍",
    "Inactive": "非活躍", "INACTIVE": "非活躍",
    "Pending": "待處理", "PENDING": "待處理",
    "Completed": "已完成", "COMPLETED": "已完成",
    "Failed": "失敗", "FAILED": "失敗",
    "Unknown": "未知", "UNKNOWN": "未知",
    "Required": "必填", "REQUIRED": "必填",
    "Optional": "選填", "OPTIONAL": "選填",
    "Untitled": "未命名", "UNTITLED": "未命名",

    # === 金融 / 分析 ===
    "CATEGORY": "分類", "Category": "分類", "CATEGORIES": "分類",
    "RISK METRICS": "風險指標", "Risk Metrics": "風險指標",
    "PORTFOLIO": "投資組合", "Portfolio": "投資組合",
    "MARKET": "市場", "Market": "市場",
    "STOCK": "股票", "Stock": "股票", "STOCKS": "股票",
    "BOND": "債券", "Bond": "債券", "BONDS": "債券",
    "ETF": "ETF", "INDEX": "指數", "Index": "指數",
    "CRYPTO": "加密貨幣", "Crypto": "加密貨幣",
    "FOREX": "外匯", "Forex": "外匯",
    "COMMODITY": "商品", "Commodity": "商品", "COMMODITIES": "商品",
    "EQUITY": "權益", "Equity": "權益", "EQUITIES": "權益",
    "DERIVATIVES": "衍生品", "Derivatives": "衍生品",
    "OPTIONS": "選擇權", "FUTURES": "期貨", "Futures": "期貨",
    "SECTOR": "類股", "Sector": "類股", "SECTORS": "類股",
    "INDUSTRY": "產業", "Industry": "產業",
    "EXCHANGE": "交易所", "Exchange": "交易所",
    "TICKER": "股票代碼", "Ticker": "股票代碼",
    "SYMBOL": "代碼", "Symbol": "代碼",
    "VOLUME": "成交量", "Volume": "成交量",
    "OPEN": "開盤", "Open": "開盤",
    "HIGH": "最高", "High": "最高",
    "LOW": "最低", "Low": "最低",
    "CHANGE": "漲跌", "Change": "漲跌",
    "RETURN": "報酬", "Return": "報酬", "RETURNS": "報酬",
    "YIELD": "收益率", "Yield": "收益率",
    "DIVIDEND": "股息", "Dividend": "股息", "DIVIDENDS": "股息",
    "EARNINGS": "收益", "Earnings": "收益",
    "REVENUE": "營收", "Revenue": "營收",
    "PROFIT": "利潤", "Profit": "利潤",
    "LOSS": "虧損", "Loss": "虧損",
    "MARGIN": "利潤率", "Margin": "利潤率",
    "RATIO": "比率", "Ratio": "比率",
    "BENCHMARK": "基準", "Benchmark": "基準",
    "PERFORMANCE": "績效", "Performance": "績效",
    "ALLOCATION": "配置", "Allocation": "配置",
    "DIVERSIFICATION": "分散化", "Diversification": "分散化",
    "CORRELATION": "相關性", "Correlation": "相關性",
    "VOLATILITY": "波動率", "Volatility": "波動率",
    "DRAWDOWN": "回撤", "Drawdown": "回撤",
    "SHARPE": "夏普比率", "Sharpe": "夏普比率",
    "ALPHA": "Alpha", "BETA": "Beta",
    "BUY": "買入", "Buy": "買入",
    "SELL": "賣出", "Sell": "賣出",
    "HOLD": "持有", "Hold": "持有",
    "LONG": "做多", "Long": "做多",
    "SHORT": "做空", "Short": "做空",
    "POSITION": "部位", "Position": "部位", "POSITIONS": "部位",
    "ORDER": "訂單", "Order": "訂單", "ORDERS": "訂單",
    "TRADE": "交易", "Trade": "交易", "TRADES": "交易",
    "BALANCE": "餘額", "Balance": "餘額",
    "ASSET": "資產", "Asset": "資產", "ASSETS": "資產",
    "LIABILITY": "負債", "Liability": "負債",
    "NET WORTH": "淨值", "Net Worth": "淨值",
    "MARKET CAP": "市值", "Market Cap": "市值",
    "P/E": "本益比", "PE Ratio": "本益比",
    "EPS": "每股盈餘",
    "ROI": "投資報酬率", "ROE": "股東權益報酬率",
    "CASH FLOW": "現金流", "Cash Flow": "現金流",
    "DEBT": "債務", "Debt": "債務",
    "GROWTH": "成長", "Growth": "成長",
    "RISK": "風險", "Risk": "風險",
    "HEDGE": "避險", "Hedge": "避險",
    "STRATEGY": "策略", "Strategy": "策略", "STRATEGIES": "策略",
    "BACKTEST": "回測", "Backtest": "回測", "BACKTESTING": "回測",
    "SIGNAL": "訊號", "Signal": "訊號", "SIGNALS": "訊號",
    "INDICATOR": "指標", "Indicator": "指標", "INDICATORS": "指標",
    "CHART": "圖表", "Chart": "圖表", "CHARTS": "圖表",
    "TABLE": "表格", "Table": "表格",
    "GRAPH": "圖形", "Graph": "圖形",
    "REPORT": "報告", "Report": "報告", "REPORTS": "報告",
    "ANALYSIS": "分析", "Analysis": "分析",
    "ANALYTICS": "分析", "Analytics": "分析",
    "FORECAST": "預測", "Forecast": "預測",
    "PREDICTION": "預測", "Prediction": "預測",
    "MODEL": "模型", "Model": "模型", "MODELS": "模型",
    "ALGORITHM": "演算法", "Algorithm": "演算法",
    "OPTIMIZER": "最佳化工具", "Optimizer": "最佳化工具",
    "SCANNER": "掃描器", "Scanner": "掃描器",
    "SCREENER": "篩選器", "Screener": "篩選器",
    "WATCHLIST": "觀察清單", "Watchlist": "觀察清單",
    "ALERT": "警示", "Alert": "警示", "ALERTS": "警示",
    "NEWS": "新聞", "News": "新聞",
    "RESEARCH": "研究", "Research": "研究",
    "ECONOMIC": "經濟", "Economic": "經濟",
    "CALENDAR": "行事曆", "Calendar": "行事曆",
    "EVENT": "事件", "Event": "事件", "EVENTS": "事件",
    "SENTIMENT": "情緒", "Sentiment": "情緒",
    "BULLISH": "看漲", "Bullish": "看漲",
    "BEARISH": "看跌", "Bearish": "看跌",
    "NEUTRAL": "中性", "Neutral": "中性",
    "OVERBOUGHT": "超買", "Overbought": "超買",
    "OVERSOLD": "超賣", "Oversold": "超賣",
    "SUPPORT": "支撐", "Support": "支撐",
    "RESISTANCE": "壓力", "Resistance": "壓力",
    "BREAKOUT": "突破", "Breakout": "突破",
    "TREND": "趨勢", "Trend": "趨勢",
    "UPTREND": "上升趨勢", "Uptrend": "上升趨勢",
    "DOWNTREND": "下降趨勢", "Downtrend": "下降趨勢",
    "REVERSAL": "反轉", "Reversal": "反轉",
    "CONSOLIDATION": "盤整", "Consolidation": "盤整",
    "MOMENTUM": "動量", "Momentum": "動量",
    "LIQUIDITY": "流動性", "Liquidity": "流動性",
    "SPREAD": "價差", "Spread": "價差",
    "PREMIUM": "溢價", "Premium": "溢價",
    "DISCOUNT": "折價", "Discount": "折價",
    "FEE": "手續費", "Fee": "手續費", "FEES": "手續費",
    "COMMISSION": "佣金", "Commission": "佣金",
    "TAX": "稅務", "Tax": "稅務",
    "INFLATION": "通膨", "Inflation": "通膨",
    "GDP": "GDP", "CPI": "CPI",
    "INTEREST RATE": "利率", "Interest Rate": "利率",
    "MOVING AVERAGE": "移動平均線", "Moving Average": "移動平均線",
    "RSI": "RSI", "MACD": "MACD", "VWAP": "VWAP",
    "BOLLINGER": "布林帶",
    "FIBONACCI": "費波那契",

    # === M&A 併購 ===
    "ACQUIRER": "收購方", "Acquirer": "收購方",
    "TARGET": "標的", "Target": "標的",
    "DEAL": "交易", "Deal": "交易", "DEALS": "交易",
    "MERGER": "合併", "Merger": "合併", "MERGERS": "合併",
    "ACQUISITION": "收購", "Acquisition": "收購",
    "SYNERGIES": "綜效", "Synergies": "綜效",
    "DUE DILIGENCE": "盡職調查", "Due Diligence": "盡職調查",
    "VALUATION": "估值", "Valuation": "估值",

    # === AI / 量化 ===
    "AI QUANT LAB": "AI 量化實驗室",
    "QUANT": "量化", "Quant": "量化",
    "MACHINE LEARNING": "機器學習", "Machine Learning": "機器學習",
    "DEEP LEARNING": "深度學習", "Deep Learning": "深度學習",
    "NEURAL NETWORK": "神經網路", "Neural Network": "神經網路",
    "TRAINING": "訓練", "Training": "訓練",
    "INFERENCE": "推論", "Inference": "推論",
    "DATASET": "資料集", "Dataset": "資料集",
    "FEATURE": "特徵", "Feature": "特徵", "FEATURES": "特徵",
    "PARAMETER": "參數", "Parameter": "參數", "PARAMETERS": "參數",
    "EPOCH": "輪次", "Epoch": "輪次",
    "ACCURACY": "準確率", "Accuracy": "準確率",
    "PRECISION": "精確率", "Precision": "精確率",
    "RECALL": "召回率", "Recall": "召回率",
    "CONFIDENCE": "信心度", "Confidence": "信心度",
    "OPTIMIZE": "最佳化", "Optimize": "最佳化",
    "SIMULATION": "模擬", "Simulation": "模擬",

    # === 圖表 / 資料 ===
    "CANDLESTICK": "K線圖", "Candlestick": "K線圖",
    "LINE CHART": "折線圖", "Line Chart": "折線圖",
    "BAR CHART": "長條圖", "Bar Chart": "長條圖",
    "PIE CHART": "圓餅圖", "Pie Chart": "圓餅圖",
    "HEATMAP": "熱力圖", "Heatmap": "熱力圖",
    "SCATTER": "散佈圖", "Scatter": "散佈圖",
    "TREEMAP": "矩形樹圖", "Treemap": "矩形樹圖",
    "TIMELINE": "時間軸", "Timeline": "時間軸",
    "LEGEND": "圖例", "Legend": "圖例",
    "AXIS": "軸", "Axis": "軸",
    "LABEL": "標籤", "Label": "標籤",
    "TOOLTIP": "提示框", "Tooltip": "提示框",
    "ZOOM": "縮放", "Zoom": "縮放",
    "PAN": "平移", "Pan": "平移",
    "FULLSCREEN": "全螢幕", "Fullscreen": "全螢幕",

    # === 長句 ===
    "No contributors yet": "尚無貢獻者",
    "No data available": "無可用資料",
    "No data": "無資料",
    "No results found": "未找到結果",
    "No results": "無結果",
    "No items": "無項目",
    "No data to display": "無資料可顯示",
    "Click to expand": "點擊展開",
    "Click to collapse": "點擊收合",
    "Drag to reorder": "拖曳以重新排序",
    "Select all": "全選",
    "Deselect all": "取消全選",
    "Sort by": "排序依據",
    "Filter by": "篩選依據",
    "Group by": "分組依據",
    "Search...": "搜尋...",
    "Search here...": "在此搜尋...",
    "Type to search...": "輸入以搜尋...",
    "Enter ticker symbol...": "輸入股票代碼...",
    "Enter keyword...": "輸入關鍵字...",
    "Please wait...": "請稍候...",
    "Processing...": "處理中...",
    "Saving...": "儲存中...",
    "Exporting...": "匯出中...",
    "Connecting...": "連線中...",
    "Disconnected": "已斷線",
    "Connected": "已連線",
    "Connection lost": "連線中斷",
    "Connection failed": "連線失敗",
    "Session expired": "工作階段已過期",
    "Access denied": "存取被拒",
    "Permission denied": "權限不足",
    "Not found": "找不到",
    "Invalid input": "無效輸入",
    "Something went wrong": "發生錯誤",
    "Try again": "請重試",
    "Try again later": "請稍後再試",
    "Are you sure?": "確定嗎？",
    "This action cannot be undone": "此操作無法復原",
    "Changes saved": "變更已儲存",
    "Changes saved successfully": "變更已成功儲存",
    "Copied to clipboard": "已複製到剪貼簿",
    "No recent reports": "無近期報告",
    "(No recent reports)": "(無近期報告)",
    "COMING SOON": "即將推出",
    "Coming Soon": "即將推出",
    "BETA": "測試版",
    "EXPERIMENTAL": "實驗性",
    "DEPRECATED": "已棄用",
    "MAINTENANCE": "維護中",
    "OFFLINE": "離線",
    "ONLINE": "線上",
    "LIVE": "即時",
    "DELAYED": "延遲",
    "REAL-TIME": "即時",
    "HISTORICAL": "歷史",
    "DAILY": "每日",
    "WEEKLY": "每週",
    "MONTHLY": "每月",
    "QUARTERLY": "每季",
    "ANNUALLY": "每年",
    "YEARLY": "每年",
    "YTD": "年初至今",
    "MTD": "月初至今",
    "QTD": "季初至今",
    "1D": "1日", "1W": "1週", "1M": "1月", "3M": "3月",
    "6M": "6月", "1Y": "1年", "3Y": "3年", "5Y": "5年",
    "MAX": "最大",
    "MIN": "最小",
    "AVG": "平均",
    "MEDIAN": "中位數",
    "STD": "標準差",
    "VAR": "變異數",
    "SUM": "總和",
    "COUNT": "計數",
    "PERCENT": "百分比",
    "RANK": "排名",
    "WEIGHT": "權重",
    "SCORE": "分數",
    "RATING": "評等",
    "GRADE": "等級",
    "TIER": "層級",
    "LEVEL": "等級",
    "PHASE": "階段",
    "STEP": "步驟",
    "STAGE": "階段",

    # 長句：搜尋/佔位符
    "Search deals by target, acquirer, or industry...": "依標的、收購方或產業搜尋交易...",
    "Search by ticker, name, or sector...": "依代碼、名稱或類股搜尋...",
    "Enter ticker or company name": "輸入股票代碼或公司名稱",
    "Enter command or search...": "輸入指令或搜尋...",
    "Type a command...": "輸入指令...",
    "Press Enter to execute": "按 Enter 執行",
    "No matching commands": "無符合的指令",
    "Recent commands": "最近的指令",
    "Frequently used": "常用",
    "Quick access": "快速存取",
}

# 也加上格式字串翻譯
FORMAT_DICT = {
    "%1 of %2 events": "%2 個事件中的 %1 個",
    "%1 holding(s) excluded — no live price.": "已排除 %1 檔持倉 — 無即時報價。",
    "%1 / week (USDC) — %2% weekly real yield at %3 stake": "%1 / 週 (USDC) — %2% 每週實際收益率，質押 %3",
    "·  %1 unverified%2": "·  %1 筆未驗證%2",
    "·  %1 without price": "·  %1 筆無報價",
}
DICT.update(FORMAT_DICT)

# === 片語模式翻譯 (用正則) ===
PHRASE_PATTERNS = [
    (r'^TOTAL\s+(.+)$', lambda m: f"總{m.group(1)}"),
    (r'^NO\s+(.+)\s+FOUND$', lambda m: f"未找到{m.group(1)}"),
    (r'^ENTER\s+(.+)$', lambda m: f"輸入{m.group(1)}"),
    (r'^SELECT\s+(.+)$', lambda m: f"選擇{m.group(1)}"),
    (r'^SHOW\s+(.+)$', lambda m: f"顯示{m.group(1)}"),
    (r'^HIDE\s+(.+)$', lambda m: f"隱藏{m.group(1)}"),
]

def translate(source):
    """嘗試翻譯，返回翻譯結果或 None"""
    s = source.strip()
    
    # 精確匹配
    if s in DICT:
        return DICT[s]
    
    # 正則模式匹配
    for pat, repl in PHRASE_PATTERNS:
        m = re.match(pat, s, re.IGNORECASE)
        if m:
            return repl(m)
    
    return None

def main():
    with open(TS_PATH, 'r') as f:
        content = f.read()
    
    translated = 0
    skipped = 0
    
    def replacer(m):
        nonlocal translated, skipped
        source = m.group(1)
        old_trans = m.group(2)
        
        result = translate(source)
        if result:
            translated += 1
            return f'<source>{source}</source>\n        <translation>{result}</translation>'
        else:
            skipped += 1
            return m.group(0)
    
    pattern = r'<source>(.*?)</source>\s*<translation type="unfinished">(.*?)</translation>'
    content = re.sub(pattern, replacer, content, flags=re.DOTALL)
    
    with open(TS_PATH, 'w') as f:
        f.write(content)
    
    remaining = len(re.findall(r'type="unfinished"', content))
    print(f"✅ 翻譯完成: {translated} 條")
    print(f"⏭️ 跳過(無匹配): {skipped} 條")
    print(f"📊 剩餘 unfinished: {remaining} 條")

if __name__ == '__main__':
    main()
